# Puzzle 151: Association rule mining x Apriori candidate pruning
# Market-basket analysis: 5,000 baskets over 200 items, generated by 25
# hidden itemsets that co-occur (each planted in 3 to 8 percent of
# baskets) plus random noise items and one ubiquitous item present in
# 70% of baskets. Find every itemset bought together in at least 2% of
# baskets, then the rules "if these, then that" with their confidence
# and lift. Association rule mining is the algorithm: count supports
# level by level, size 1, then 2, then 3, and read rules off the
# frequent sets. Apriori's candidate pruning is the heuristic: every
# subset of a frequent itemset is frequent, so a size-k candidate is
# only counted if all of its size-(k-1) subsets were frequent; the
# lattice above an infrequent set is never touched.
#
# Referees:
# (1) THE EXACT ANSWER: the frequent itemsets found by Apriori at every
#     size equal those found by exhaustive counting (every subset of
#     every basket up to size 5, tallied), and every planted itemset is
#     among them;
# (2) THE PRUNING, counted: candidates generated by the join step
#     alone versus after the subset prune, at every level, and the
#     resulting candidate-times-basket containment tests, against the
#     count that brute force over all 2- and 3-subsets of 200 items
#     would need (not run: 6.7 billion tests). AUTHOR NOTE: at 1%
#     support nearly every item was frequent from noise alone and
#     level 2, which no subset prune can touch, was 90 million tests
#     of the 168 million; the threshold is 2% so the planted structure
#     is what gets mined, and the saving is reported where it lives,
#     at levels 3 and up;
# (3) THE RULES: confidence and lift from the frequent sets; every
#     planted rule has lift above 2, and the ubiquitous item shows the
#     confidence trap: rules pointing at it have confidence near 0.7
#     and lift near 1.0, no information at all;
# (4) THE SUPPORT SWEEP: minimum support 1%, 2%, 3%, 5% and the
#     number of frequent sets, candidates, and tests at each;
# (5) THE RIVAL: Eclat, vertical tid-set intersection depth first,
#     returns the same frequent sets with its work counted in tid-set
#     elements touched, against Apriori's containment tests.
import math
import random
from collections import Counter, defaultdict
from itertools import combinations

SEED = 20260926
N_ITEMS = 200
N_BASKETS = 5000
N_PLANTED = 25
UBIQUITOUS = 0
MIN_SUPPORT = 0.02
MAX_SIZE = 5


def make_baskets(rng):
    items = list(range(1, N_ITEMS))
    planted = []
    for _ in range(N_PLANTED):
        size = rng.choice([2, 2, 3, 3, 4, 5])
        planted.append((frozenset(rng.sample(items, size)), rng.uniform(0.03, 0.08)))
    baskets = []
    for _ in range(N_BASKETS):
        basket = set()
        for itemset, p in planted:
            if rng.random() < p:
                basket |= itemset
        for _ in range(rng.randint(2, 4)):
            basket.add(rng.choice(items))
        if rng.random() < 0.7:
            basket.add(UBIQUITOUS)
        baskets.append(frozenset(basket))
    return baskets, planted


def exhaustive(baskets, min_count, max_size):
    """The referee: tally every subset of every basket up to max_size."""
    counts = Counter()
    for b in baskets:
        items = sorted(b)
        for k in range(1, min(max_size, len(items)) + 1):
            for combo in combinations(items, k):
                counts[frozenset(combo)] += 1
    frequent = defaultdict(dict)
    for s, c in counts.items():
        if c >= min_count:
            frequent[len(s)][s] = c
    return frequent, sum(math.comb(len(b), k) for b in baskets for k in range(1, min(max_size, len(b)) + 1))


def apriori(baskets, min_count, max_size, prune=True):
    stats = {'join': [], 'pruned': [], 'tests': 0, 'scans': 0, 'level_tests': [0]}
    item_counts = Counter(i for b in baskets for i in b)
    stats['scans'] += 1
    level = {frozenset([i]): c for i, c in item_counts.items() if c >= min_count}
    frequent = {1: level}
    stats['join'].append(len(item_counts))
    stats['pruned'].append(len(item_counts))
    k = 2
    while level and k <= max_size:
        prev = sorted(level, key=sorted)
        joined = set()
        for a, b in combinations(prev, 2):
            if sorted(a)[:-1] == sorted(b)[:-1]:
                joined.add(a | b)
        stats['join'].append(len(joined))
        if prune:
            cands = [c for c in joined if all(frozenset(sub) in level for sub in combinations(sorted(c), k - 1))]
        else:
            cands = list(joined)
        stats['pruned'].append(len(cands))
        counts = Counter()
        stats['scans'] += 1
        stats['level_tests'].append(len(cands) * len(baskets))
        stats['tests'] += len(cands) * len(baskets)
        for c in cands:
            for b in baskets:
                if c <= b:
                    counts[c] += 1
        level = {c: n for c, n in counts.items() if n >= min_count}
        if level:
            frequent[k] = level
        k += 1
    return frequent, stats


def eclat(baskets, min_count, max_size):
    tids = defaultdict(set)
    for t, b in enumerate(baskets):
        for i in b:
            tids[i].add(t)
    work = [0]
    frequent = defaultdict(dict)

    def dfs(prefix, items):
        for idx, (i, ti) in enumerate(items):
            s = prefix | {i}
            frequent[len(s)][frozenset(s)] = len(ti)
            if len(s) >= max_size:
                continue
            nxt = []
            for j, tj in items[idx + 1:]:
                work[0] += len(ti) + len(tj)
                inter = ti & tj
                if len(inter) >= min_count:
                    nxt.append((j, inter))
            if nxt:
                dfs(s, nxt)
    start = sorted((i, t) for i, t in tids.items() if len(t) >= min_count)
    dfs(frozenset(), start)
    return frequent, work[0]


def rules(frequent, n, min_conf):
    support = {}
    for level in frequent.values():
        support.update(level)
    out = []
    for s, c in support.items():
        if len(s) < 2:
            continue
        for r in range(1, len(s)):
            for ante in combinations(sorted(s), r):
                ante = frozenset(ante)
                cons = s - ante
                conf = c / support[ante]
                if conf >= min_conf:
                    lift = conf / (support[cons] / n)
                    out.append((ante, cons, c / n, conf, lift))
    return out


if __name__ == '__main__':
    rng = random.Random(SEED)
    baskets, planted = make_baskets(rng)
    min_count = int(MIN_SUPPORT * N_BASKETS)
    mean_size = sum(len(b) for b in baskets) / N_BASKETS

    # Oracle 1: exact answer and every planted itemset.
    truth, truth_work = exhaustive(baskets, min_count, MAX_SIZE)
    found, stats = apriori(baskets, min_count, MAX_SIZE)
    for k in range(1, MAX_SIZE + 1):
        assert set(found.get(k, {})) == set(truth.get(k, {})), k
        assert all(found[k][s] == truth[k][s] for s in found.get(k, {}))
    n_frequent = sum(len(v) for v in found.values())
    planted_found = sum(1 for s, p in planted if s in found.get(len(s), {}))
    planted_expected = sum(1 for s, p in planted if truth.get(len(s), {}).get(s, 0) >= min_count)
    assert planted_found == planted_expected and planted_found >= 20, (planted_found, planted_expected)

    # Oracle 2: the pruning.
    found_np, stats_np = apriori(baskets, min_count, MAX_SIZE, prune=False)
    assert {k: set(v) for k, v in found_np.items()} == {k: set(v) for k, v in found.items()}
    # level 2 cannot be pruned (every singleton subset of a pair of frequent
    # items is frequent), so the saving is at levels 3 and up, measured there
    deep = sum(stats['level_tests'][2:])
    deep_np = sum(stats_np['level_tests'][2:])
    assert stats['tests'] < stats_np['tests'] and deep < deep_np / 4, (stats['tests'], stats_np['tests'], deep, deep_np)
    brute_23 = (math.comb(N_ITEMS, 2) + math.comb(N_ITEMS, 3)) * N_BASKETS

    # Oracle 3: rules and the confidence trap.
    rs = rules(found, N_BASKETS, 0.6)
    planted_rules = [r for r in rs if (r[0] | r[1]) in {s for s, _ in planted}]
    assert planted_rules and min(r[4] for r in planted_rules) > 2, min(r[4] for r in planted_rules)
    trap = [r for r in rs if r[1] == frozenset([UBIQUITOUS])]
    assert trap and max(r[4] for r in trap) < 1.3 and min(r[3] for r in trap) >= 0.6, (len(trap), max(r[4] for r in trap))

    # Oracle 4: the support sweep.
    sweep = []
    for sup in (0.01, 0.02, 0.03, 0.05):
        mc = int(sup * N_BASKETS)
        f, st = apriori(baskets, mc, MAX_SIZE)
        sweep.append((sup, sum(len(v) for v in f.values()), sum(st['pruned']), st['tests']))
    assert sweep[0][1] > sweep[1][1] > sweep[2][1] > sweep[3][1], sweep

    # Oracle 5: Eclat.
    fe, eclat_work = eclat(baskets, min_count, MAX_SIZE)
    assert {k: set(v) for k, v in fe.items()} == {k: set(v) for k, v in found.items()}

    print(f'contest: {N_BASKETS:,} baskets over {N_ITEMS} items ({mean_size:.1f} items per basket), {N_PLANTED} planted itemsets, item 0 in 70% of baskets; minimum support {MIN_SUPPORT:.0%} ({min_count} baskets); referee: exhaustive subset counting ({truth_work:,} subsets tallied)')
    print(f'frequent itemsets: {n_frequent} ({", ".join(f"size {k}: {len(v)}" for k, v in sorted(found.items()))}), identical to the referee at every size; {planted_found} of {N_PLANTED} planted itemsets frequent ({N_PLANTED - planted_expected} planted below the threshold by chance)')
    print(f"  {'level':>5} {'join candidates':>15} {'after prune':>11} {'tests, pruned':>14} {'tests, unpruned':>16}")
    for k, (j, p, t, tn) in enumerate(zip(stats['join'], stats['pruned'], stats['level_tests'], stats_np['level_tests']), start=1):
        print(f'  {k:>5} {j:>15,} {p:>11,} {t:>14,} {tn:>16,}')
    print(f'containment tests: {stats["tests"]:,} with pruning, {stats_np["tests"]:,} without ({stats["scans"]} scans); levels 3 and up: {deep:,} vs {deep_np:,}; level 2 is the bottleneck no subset prune can touch; brute force over all 2- and 3-subsets of {N_ITEMS} items would need {brute_23:,} (not run)')
    print(f'rules at confidence 0.6: {len(rs)}; planted rules: lift {min(r[4] for r in planted_rules):.1f} to {max(r[4] for r in planted_rules):.1f}; {len(trap)} rules point at the ubiquitous item with confidence {min(r[3] for r in trap):.2f} to {max(r[3] for r in trap):.2f} and lift {min(r[4] for r in trap):.2f} to {max(r[4] for r in trap):.2f}')
    print(f"  {'min support':>11} {'frequent sets':>13} {'candidates':>10} {'tests':>12}")
    for sup, nf, nc, nt in sweep:
        print(f'  {sup:>11.1%} {nf:>13} {nc:>10,} {nt:>12,}')
    print(f'Eclat: same {sum(len(v) for v in fe.values())} frequent sets from tid-set intersections touching {eclat_work:,} elements, against Apriori\'s {stats["tests"]:,} containment tests')
    print(f'OK: Apriori equals exhaustive counting at every size ({n_frequent} frequent sets); pruning cuts containment tests from {stats_np["tests"]:,} to {stats["tests"]:,} ({deep_np:,} to {deep:,} above level 2); '
          f'planted rules lift above 2 and the ubiquitous item\'s rules sit at lift about 1; the sweep is monotone; Eclat agrees')
