# Puzzle 149: Decision tree x information gain splits
# Interpretable classification: 2,000 labeled examples with six
# numeric features and one categorical feature, generated by a hidden
# rule that is itself a small tree (the answer depends on x1, and only
# below a threshold of x1 does the category and x3 matter), with 10%
# of the labels flipped. Learn a classifier that a person can read.
# The decision tree is the algorithm: split the data on one feature at
# one threshold, recurse on each side, stop at a depth or a minimum
# leaf, and predict the majority at each leaf. The heuristic is the
# split criterion: information gain, the drop in label entropy from
# the split, chosen greedily over every feature and threshold at every
# node.
#
# Referees:
# (1) THE RULE: the tree's root must be the generating rule's root
#     (x1 at a threshold within 0.05 of 0.6), and the test accuracy
#     must land within 3 points of the Bayes rate, 90%, that the label
#     noise allows;
# (2) THE CRITERIA at the same depth: information gain, Gini impurity,
#     misclassification error, and random splits, measured as test
#     accuracy; the two impurity measures must beat random splits;
# (3) THE TRAP, measured: with a unique identifier attribute in the
#     feature set and ID3-style multiway splits (one branch per value),
#     information gain picks the identifier at the root, since its gain
#     is the whole entropy, and the tree becomes a lookup table whose
#     test accuracy is the majority rate; Quinlan's gain ratio divides
#     by the split's own entropy, refuses it, and recovers the rule.
#     AUTHOR NOTE: the draft expected the trap under binary one-vs-rest
#     splits and it did not occur (isolating one row gains almost
#     nothing), which is itself the reason CART-style binary splits are
#     immune; both facts are measured;
# (4) THE DEPTH SWEEP: train and test accuracy at depths 1, 2, 4, 6,
#     10, and unlimited, showing the unlimited tree memorize the noise
#     (train near 100%, test below the depth-6 tree), and reduced-error
#     pruning on a validation set repair most of it;
# (5) THE RIVALS, measured on the same test set: a random forest of 30
#     trees (at least as accurate, unreadable), Gaussian naive Bayes,
#     and logistic regression, which cannot represent the interaction
#     and lands well below the tree.
import math
import random
from collections import Counter

SEED = 20260926
NOISE = 0.10
N_TRAIN, N_VAL, N_TEST = 2000, 500, 2000
CATS = ['A', 'B', 'C', 'D']


def rule(x, c):
    if x[0] > 0.6:
        return 1 if x[1] > 0.2 else 0
    return 1 if (c in ('A', 'B') and x[2] > 0.7) else 0


def make_data(n, rng, with_id=False, start_id=0):
    rows = []
    for i in range(n):
        x = [rng.random() for _ in range(6)]
        c = rng.choice(CATS)
        y = rule(x, c)
        if rng.random() < NOISE:
            y = 1 - y
        feats = x + [c]
        if with_id:
            feats = feats + [f'id{start_id + i}']
        rows.append((feats, y))
    return rows


def entropy(counts):
    n = sum(counts.values())
    return -sum(c / n * math.log2(c / n) for c in counts.values() if c)


def gini(counts):
    n = sum(counts.values())
    return 1 - sum((c / n) ** 2 for c in counts.values())


def miscls(counts):
    n = sum(counts.values())
    return 1 - max(counts.values()) / n


IMPURITY = {'entropy': entropy, 'gini': gini, 'miscls': miscls, 'gainratio': entropy, 'random': entropy}


def split_score(criterion, parent, parts):
    """Impurity drop of a split into `parts` (a list of Counters); gain ratio
    divides by the entropy of the part sizes."""
    n = sum(parent.values())
    sizes = [sum(p.values()) for p in parts]
    if any(s == 0 for s in sizes):
        return -1.0
    imp = IMPURITY[criterion]
    gain = imp(parent) - sum(s / n * imp(p) for s, p in zip(sizes, parts))
    if criterion == 'gainratio':
        split_info = entropy(Counter({i: s for i, s in enumerate(sizes)}))
        return gain / split_info if split_info > 0 else 0.0
    return gain


def best_split(rows, criterion, features, rng, multiway=False):
    """Every candidate split scored; for gain ratio, Quinlan's rule: rank by
    gain ratio only among candidates whose plain gain is at least the average
    gain, which stops the ratio from rewarding trivial lopsided splits."""
    parent = Counter(y for _, y in rows)
    cands = []                                   # (score, gain, f, test)

    def consider(parts, f, test):
        gain = split_score('entropy', parent, parts)
        if gain < 0:
            return
        score = rng.random() if criterion == 'random' else split_score(criterion, parent, parts)
        cands.append((score, gain, f, test))

    for f in features:
        values = [r[0][f] for r in rows]
        if isinstance(values[0], str):
            if multiway:
                # ID3 style: one branch per value
                parts = {}
                for (x, y) in rows:
                    parts.setdefault(x[f], Counter())[y] += 1
                if len(parts) >= 2:
                    consider(list(parts.values()), f, ('multi', None))
            else:
                # CART style: one value against the rest
                for v in set(values):
                    left = Counter(y for (x, y) in rows if x[f] == v)
                    consider([left, parent - left], f, ('eq', v))
        else:
            order = sorted(range(len(rows)), key=lambda i: values[i])
            left = Counter()
            for k in range(len(rows) - 1):
                left[rows[order[k]][1]] += 1
                if values[order[k]] == values[order[k + 1]]:
                    continue
                thr = (values[order[k]] + values[order[k + 1]]) / 2
                consider([Counter(left), parent - left], f, ('lt', thr))
    if not cands:
        return (-1.0, None, None)
    if criterion == 'gainratio':
        mean_gain = sum(c[1] for c in cands) / len(cands)
        cands = [c for c in cands if c[1] >= mean_gain]
    score, gain, f, test = max(cands, key=lambda c: c[0])
    return (score, f, test)


def goes_left(x, f, test):
    kind, v = test
    return x[f] == v if kind == 'eq' else x[f] < v


def build(rows, criterion, max_depth, min_leaf, rng, feature_subset=None, multiway=False, depth=0):
    counts = Counter(y for _, y in rows)
    majority = counts.most_common(1)[0][0]
    leaf = {'leaf': majority, 'n': len(rows), 'counts': counts}
    if depth == max_depth or len(rows) < 2 * min_leaf or len(counts) == 1:
        return leaf
    feats = list(range(len(rows[0][0])))
    if feature_subset is not None:
        feats = rng.sample(feats, feature_subset)
    score, f, test = best_split(rows, criterion, feats, rng, multiway)
    if f is None or score <= 0:
        return leaf
    node = {'f': f, 'test': test, 'n': len(rows), 'counts': counts, 'majority': majority}
    if test[0] == 'multi':
        groups = {}
        for r in rows:
            groups.setdefault(r[0][f], []).append(r)
        node['children'] = {v: build(g, criterion, max_depth, min_leaf, rng, feature_subset, multiway, depth + 1) for v, g in groups.items()}
        return node
    left_rows = [r for r in rows if goes_left(r[0], f, test)]
    right_rows = [r for r in rows if not goes_left(r[0], f, test)]
    if len(left_rows) < min_leaf or len(right_rows) < min_leaf:
        return leaf
    node['left'] = build(left_rows, criterion, max_depth, min_leaf, rng, feature_subset, multiway, depth + 1)
    node['right'] = build(right_rows, criterion, max_depth, min_leaf, rng, feature_subset, multiway, depth + 1)
    return node


def predict(tree, x):
    while 'leaf' not in tree:
        if 'children' in tree:
            child = tree['children'].get(x[tree['f']])
            if child is None:
                return tree['majority']          # an unseen value: fall back to the node majority
            tree = child
        else:
            tree = tree['left'] if goes_left(x, tree['f'], tree['test']) else tree['right']
    return tree['leaf']


def accuracy(tree, rows):
    return sum(predict(tree, x) == y for x, y in rows) / len(rows)


def leaves(tree):
    if 'leaf' in tree:
        return 1
    if 'children' in tree:
        return sum(leaves(c) for c in tree['children'].values())
    return leaves(tree['left']) + leaves(tree['right'])


def prune(tree, val_rows):
    """Reduced-error pruning: replace a subtree by its majority leaf whenever
    that does not lower accuracy on the validation rows that reach it."""
    if 'leaf' in tree:
        return tree
    left_rows = [r for r in val_rows if goes_left(r[0], tree['f'], tree['test'])]
    right_rows = [r for r in val_rows if not goes_left(r[0], tree['f'], tree['test'])]
    tree['left'] = prune(tree['left'], left_rows)
    tree['right'] = prune(tree['right'], right_rows)
    if not val_rows:
        return tree
    as_is = sum(predict(tree, x) == y for x, y in val_rows)
    as_leaf = sum(tree['majority'] == y for _, y in val_rows)
    if as_leaf >= as_is:
        return {'leaf': tree['majority'], 'n': tree['n'], 'counts': tree['counts']}
    return tree


def forest_predict(trees, x):
    votes = Counter(predict(t, x) for t in trees)
    return votes.most_common(1)[0][0]


def naive_bayes(train):
    """Gaussian for numeric features, frequency tables for the category."""
    model = {}
    for y in (0, 1):
        rows = [x for x, yy in train if yy == y]
        prior = len(rows) / len(train)
        stats = []
        for f in range(6):
            vals = [x[f] for x in rows]
            mu = sum(vals) / len(vals)
            var = sum((v - mu) ** 2 for v in vals) / len(vals) + 1e-9
            stats.append((mu, var))
        cat = Counter(x[6] for x in rows)
        model[y] = (prior, stats, cat, len(rows))

    def pred(x):
        best, best_y = -1e300, None
        for y, (prior, stats, cat, n) in model.items():
            lp = math.log(prior)
            for f, (mu, var) in enumerate(stats):
                lp += -0.5 * math.log(2 * math.pi * var) - (x[f] - mu) ** 2 / (2 * var)
            lp += math.log((cat[x[6]] + 1) / (n + len(CATS)))
            if lp > best:
                best, best_y = lp, y
        return best_y
    return pred


def logistic_regression(train, epochs=300, lr=0.5):
    def featurize(x):
        return x[:6] + [1.0 if x[6] == c else 0.0 for c in CATS] + [1.0]
    X = [featurize(x) for x, _ in train]
    Y = [y for _, y in train]
    w = [0.0] * len(X[0])
    for _ in range(epochs):
        grad = [0.0] * len(w)
        for xi, yi in zip(X, Y):
            z = sum(a * b for a, b in zip(w, xi))
            p = 1 / (1 + math.exp(-max(-30, min(30, z))))
            for j, v in enumerate(xi):
                grad[j] += (p - yi) * v
        w = [wj - lr * g / len(X) for wj, g in zip(w, grad)]

    def pred(x):
        return 1 if sum(a * b for a, b in zip(w, featurize(x))) > 0 else 0
    return pred


if __name__ == '__main__':
    rng = random.Random(SEED)
    train = make_data(N_TRAIN, rng)
    val = make_data(N_VAL, rng)
    test = make_data(N_TEST, rng)
    bayes = sum(rule(x, x[6]) == y for x, y in test) / N_TEST
    majority = max(Counter(y for _, y in test).values()) / N_TEST

    # Oracle 1: the rule recovered, accuracy near the Bayes rate.
    tree = build(train, 'entropy', 6, 5, rng)
    assert tree['f'] == 0 and abs(tree['test'][1] - 0.6) < 0.05, (tree['f'], tree['test'])
    acc_tree = accuracy(tree, test)
    assert acc_tree > bayes - 0.03, (acc_tree, bayes)

    # Oracle 2: the criteria at depth 6.
    crit = {}
    for c in ('entropy', 'gini', 'miscls', 'random'):
        t = build(train, c, 6, 5, rng)
        crit[c] = (accuracy(t, test), leaves(t))
    assert crit['entropy'][0] > crit['random'][0] + 0.05 and crit['gini'][0] > crit['random'][0] + 0.05, crit
    assert abs(crit['entropy'][0] - crit['gini'][0]) < 0.03, crit

    # Oracle 3: the identifier trap (multiway splits) and the binary immunity.
    rng_id = random.Random(SEED + 1)
    train_id = make_data(N_TRAIN, rng_id, with_id=True, start_id=0)
    test_id = make_data(N_TEST, rng_id, with_id=True, start_id=N_TRAIN)
    trap = build(train_id, 'entropy', 6, 1, rng, multiway=True)
    trap_acc = accuracy(trap, test_id)
    ratio = build(train_id, 'gainratio', 6, 5, rng, multiway=True)
    ratio_acc = accuracy(ratio, test_id)
    binary = build(train_id, 'entropy', 6, 5, rng, multiway=False)
    binary_acc = accuracy(binary, test_id)
    assert trap['f'] == 7 and leaves(trap) == N_TRAIN, (trap['f'], leaves(trap))
    assert abs(trap_acc - majority) < 0.03, (trap_acc, majority)
    assert ratio['f'] == 0 and ratio_acc > bayes - 0.04, (ratio['f'], ratio_acc)
    assert binary['f'] == 0 and binary_acc > bayes - 0.04, (binary['f'], binary_acc)

    # Oracle 4: the depth sweep and pruning.
    sweep = []
    for d in (1, 2, 4, 6, 10, 99):
        t = build(train, 'entropy', d, 1, rng)
        sweep.append((d, accuracy(t, train), accuracy(t, test), leaves(t)))
    full = build(train, 'entropy', 99, 1, rng)
    full_train, full_test, full_leaves = accuracy(full, train), accuracy(full, test), leaves(full)
    assert full_train > 0.99 and full_test < acc_tree - 0.03, (full_train, full_test, acc_tree)
    pruned = prune(full, val)
    pruned_test, pruned_leaves = accuracy(pruned, test), leaves(pruned)
    assert pruned_test > full_test + 0.03 and pruned_leaves < full_leaves / 3, (pruned_test, full_test, pruned_leaves, full_leaves)

    # Oracle 5: the rivals.
    forest = []
    for _ in range(30):
        boot = [train[rng.randrange(N_TRAIN)] for _ in range(N_TRAIN)]
        forest.append(build(boot, 'entropy', 8, 2, rng, feature_subset=3))
    forest_acc = sum(forest_predict(forest, x) == y for x, y in test) / N_TEST
    nb = naive_bayes(train)
    nb_acc = sum(nb(x) == y for x, y in test) / N_TEST
    lr_model = logistic_regression(train)
    lr_acc = sum(lr_model(x) == y for x, y in test) / N_TEST
    assert forest_acc >= acc_tree - 0.01, (forest_acc, acc_tree)
    assert lr_acc < acc_tree - 0.05, (lr_acc, acc_tree)

    print(f'contest: a hidden tree rule over six numeric features and one category with {NOISE:.0%} label noise; {N_TRAIN:,} train, {N_VAL} validation, {N_TEST:,} test; referee: the rule itself (Bayes rate {bayes:.1%}; majority class {majority:.1%})')
    print(f'information gain, depth 6, min leaf 5: root splits x1 at {tree["test"][1]:.3f} (rule: 0.6), test accuracy {acc_tree:.1%}, {leaves(tree)} leaves')
    print(f"  {'criterion':>18} {'test accuracy':>14} {'leaves':>7}")
    for c, (a, l) in crit.items():
        print(f'  {c:>18} {a:>14.1%} {l:>7}')
    print(f'the identifier trap with multiway splits: information gain roots on the id column ({leaves(trap)} leaves, one per row), test accuracy {trap_acc:.1%} (majority {majority:.1%}); gain ratio roots on x1, {ratio_acc:.1%}; binary one-vs-rest splits with plain gain also root on x1, {binary_acc:.1%}')
    print(f"  {'max depth':>9} {'train':>7} {'test':>7} {'leaves':>7}")
    for d, tr, te, l in sweep:
        print(f'  {d if d < 99 else "none":>9} {tr:>7.1%} {te:>7.1%} {l:>7}')
    print(f'reduced-error pruning of the unlimited tree on {N_VAL} validation rows: {full_leaves} -> {pruned_leaves} leaves, test {full_test:.1%} -> {pruned_test:.1%}')
    print(f'rivals on the same test set: random forest (30 trees, 3 features per split) {forest_acc:.1%}; Gaussian naive Bayes {nb_acc:.1%}; logistic regression {lr_acc:.1%}')
    print(f'OK: the root recovered (x1 at {tree["test"][1]:.2f}), test {acc_tree:.1%} vs Bayes {bayes:.1%}; entropy and Gini beat random splits by 5+ points; the id trap {trap_acc:.1%} vs gain ratio {ratio_acc:.1%}; '
          f'unlimited depth {full_train:.1%} train / {full_test:.1%} test, pruned to {pruned_leaves} leaves at {pruned_test:.1%}; forest {forest_acc:.1%}, naive Bayes {nb_acc:.1%}, logistic {lr_acc:.1%}')
