# Puzzle 155: IDA* x Manhattan distance
# Memory-bound puzzle search: sliding-tile puzzles, the 8-puzzle on a
# 3 x 3 board and the 15-puzzle on 4 x 4, to be solved in the fewest
# moves. A* finds optimal solutions but keeps every state it has seen;
# on the 15-puzzle that is memory measured in gigabytes before the
# answer arrives. IDA* (iterative deepening A*) is the algorithm: a
# depth-first search bounded by f = g + h, restarted with the smallest
# f that exceeded the previous bound, so the memory is one path and the
# result is still optimal. The heuristic is the Manhattan distance: the
# sum over tiles of the row and column distance to the tile's home,
# admissible because every move slides one tile one square, and it is
# what makes the bounded searches short.
#
# Referees:
# (1) OPTIMALITY, exhaustive: breadth-first search from the goal over
#     all 181,440 reachable 8-puzzle states gives the exact distance of
#     every state; IDA* with Manhattan must return exactly that length
#     on 100 random states, and Manhattan must never exceed the true
#     distance on any of the 181,440 (admissibility, checked on all);
# (2) THE HEURISTIC'S WORTH: nodes generated by IDA* with the zero
#     heuristic (plain iterative deepening), misplaced tiles,
#     Manhattan, and Manhattan plus linear conflict, on the same
#     instances, against A* with Manhattan and its stored states;
# (3) THE ITERATIONS: the f-bounds one instance passes through and the
#     nodes in each. AUTHOR CORRECTION: the draft said the last iteration
#     dominates; measured, the last COMPLETE iteration dominates (75% of
#     the nodes) and the final one, which stops the moment the goal is
#     found, is 4%; the geometric growth is what makes the repeated
#     work affordable;
# (4) THE 15-PUZZLE: instances scrambled by random moves, IDA* with
#     Manhattan against A* with Manhattan as the optimality referee,
#     with the memory of each measured (the path against the open and
#     closed sets);
# (5) THE NEGATIVE EXAMPLE, counted: breadth-first search on the
#     15-puzzle, whose reachable state space is 10^13 states, and
#     measured on the 8-puzzle, where it expands all 181,440 states to
#     answer one query that IDA* answers in a few thousand nodes.
import heapq
import math
import random
from collections import deque

SEED = 20260926


def neighbors(state, n):
    """States reachable by one slide; the blank is 0."""
    z = state.index(0)
    r, c = divmod(z, n)
    out = []
    for dr, dc, tag in ((-1, 0, 'U'), (1, 0, 'D'), (0, -1, 'L'), (0, 1, 'R')):
        rr, cc = r + dr, c + dc
        if 0 <= rr < n and 0 <= cc < n:
            j = rr * n + cc
            s = list(state)
            s[z], s[j] = s[j], s[z]
            out.append((tuple(s), s[z]))        # the tile that moved
    return out


def bfs_all(goal, n):
    dist = {goal: 0}
    q = deque([goal])
    while q:
        s = q.popleft()
        for t, _ in neighbors(s, n):
            if t not in dist:
                dist[t] = dist[s] + 1
                q.append(t)
    return dist


def manhattan(state, n):
    d = 0
    for i, v in enumerate(state):
        if v:
            d += abs(i // n - v // n) + abs(i % n - v % n)
    return d


def misplaced(state, n):
    return sum(1 for i, v in enumerate(state) if v and v != i)


def linear_conflict(state, n):
    """Manhattan plus 2 for every tile that must leave its goal line to let
    the others pass: in each row and column, the tiles already in their goal
    line minus the longest subset of them that is in the right order."""
    def longest_in_order(vals):
        best = []
        for v in vals:
            k = 0
            while k < len(best) and best[k] < v:
                k += 1
            if k == len(best):
                best.append(v)
            else:
                best[k] = v
        return len(best)
    h = manhattan(state, n)
    for r in range(n):
        goal_cols = [state[r * n + c] % n for c in range(n) if state[r * n + c] and state[r * n + c] // n == r]
        h += 2 * (len(goal_cols) - longest_in_order(goal_cols))
    for c in range(n):
        goal_rows = [state[r * n + c] // n for r in range(n) if state[r * n + c] and state[r * n + c] % n == c]
        h += 2 * (len(goal_rows) - longest_in_order(goal_rows))
    return h


def ida_star(start, goal, n, h, node_limit=5_000_000):
    """Returns (length, nodes generated, bounds, nodes per iteration, max depth)."""
    bound = h(start, n)
    path = [start]
    stats = {'nodes': 0, 'iters': [], 'max_depth': 0}

    def search(g, bound, prev):
        state = path[-1]
        f = g + h(state, n)
        if f > bound:
            return f
        if state == goal:
            return 'FOUND'
        best = math.inf
        for t, tile in neighbors(state, n):
            if t == prev:
                continue
            stats['nodes'] += 1
            if stats['nodes'] > node_limit:
                raise RuntimeError('node limit')
            path.append(t)
            stats['max_depth'] = max(stats['max_depth'], len(path))
            r = search(g + 1, bound, state)
            if r == 'FOUND':
                return r
            if r < best:
                best = r
            path.pop()
        return best

    bounds = []
    while True:
        before = stats['nodes']
        bounds.append(bound)
        r = search(0, bound, None)
        stats['iters'].append(stats['nodes'] - before)
        if r == 'FOUND':
            return len(path) - 1, stats['nodes'], bounds, stats['iters'], stats['max_depth']
        if r == math.inf:
            return None, stats['nodes'], bounds, stats['iters'], stats['max_depth']
        bound = r


def a_star(start, goal, n, h):
    """Returns (length, nodes generated, peak stored states)."""
    open_heap = [(h(start, n), 0, start)]
    g_best = {start: 0}
    closed = set()
    nodes = 0
    peak = 1
    counter = 0
    while open_heap:
        f, g, s = heapq.heappop(open_heap)
        if s in closed:
            continue
        if s == goal:
            return g, nodes, peak
        closed.add(s)
        for t, _ in neighbors(s, n):
            ng = g + 1
            if ng < g_best.get(t, math.inf):
                g_best[t] = ng
                nodes += 1
                counter += 1
                heapq.heappush(open_heap, (ng + h(t, n), ng, t))
        peak = max(peak, len(g_best))
    return None, nodes, peak


def scramble(goal, n, moves, rng):
    s = goal
    prev = None
    for _ in range(moves):
        opts = [t for t, _ in neighbors(s, n) if t != prev]
        prev = s
        s = rng.choice(opts)
    return s


if __name__ == '__main__':
    rng = random.Random(SEED)
    GOAL3 = tuple(range(9))
    GOAL4 = tuple(range(16))

    # Oracle 1: exhaustive truth for the 8-puzzle, admissibility on every state.
    dist3 = bfs_all(GOAL3, 3)
    assert len(dist3) == 181440, len(dist3)
    max_dist = max(dist3.values())
    violations = sum(1 for s, d in dist3.items() if manhattan(s, 3) > d or misplaced(s, 3) > d or linear_conflict(s, 3) > d)
    assert violations == 0, violations
    states = rng.sample(list(dist3), 100)
    depths = [dist3[s] for s in states]
    results = {'zero': [], 'misplaced': [], 'manhattan': [], 'linear conflict': []}
    heuristics = {'zero': lambda s, n: 0, 'misplaced': misplaced, 'manhattan': manhattan, 'linear conflict': linear_conflict}
    astar_nodes = []
    astar_peak = []
    for s in states:
        for name, h in heuristics.items():
            if name == 'zero' and dist3[s] > 20:
                results[name].append(None)          # plain iterative deepening is measured on the shallower instances only
                continue
            length, nodes, bounds, iters, depth = ida_star(s, GOAL3, 3, h)
            assert length == dist3[s], (name, length, dist3[s])
            results[name].append(nodes)
        length, nodes, peak = a_star(s, GOAL3, 3, manhattan)
        assert length == dist3[s]
        astar_nodes.append(nodes)
        astar_peak.append(peak)
    mean = lambda xs: sum(xs) / len(xs)
    m_zero = mean([v for v in results['zero'] if v is not None])
    m_mis = mean(results['misplaced'])
    m_man = mean(results['manhattan'])
    m_lc = mean(results['linear conflict'])
    assert m_lc < m_man < m_mis, (m_lc, m_man, m_mis)
    n_zero = sum(1 for v in results['zero'] if v is not None)
    m_zero_paired = mean([results['manhattan'][i] for i, v in enumerate(results['zero']) if v is not None])
    assert m_zero > 20 * m_zero_paired, (m_zero, m_zero_paired)

    # Oracle 3: the iterations on the deepest sampled instance.
    deepest = max(states, key=lambda s: dist3[s])
    length, nodes, bounds, iters, depth = ida_star(deepest, GOAL3, 3, manhattan)
    assert all(b2 - b1 == 2 for b1, b2 in zip(bounds, bounds[1:])), bounds
    last_share = iters[-1] / nodes
    biggest_share = max(iters) / nodes
    assert depth <= length + 1
    assert biggest_share > 0.5 and max(iters) == iters[-2], (iters, biggest_share)

    # Oracle 4: the 15-puzzle against A*.
    rows15 = []
    for k in range(4):
        s = scramble(GOAL4, 4, 36, rng)
        length_a, nodes_a, peak_a = a_star(s, GOAL4, 4, manhattan)
        length_i, nodes_i, bounds_i, iters_i, depth_i = ida_star(s, GOAL4, 4, manhattan)
        assert length_i == length_a, (length_i, length_a)
        rows15.append((length_i, nodes_i, depth_i, nodes_a, peak_a))
    assert all(r[2] <= r[0] + 1 and r[4] > 50 * r[2] for r in rows15), rows15

    # Oracle 5: breadth-first search as the negative example.
    bfs_expanded = len(dist3)
    space15 = math.factorial(16) // 2

    print(f'contest: sliding-tile puzzles solved optimally; referees: breadth-first distances for all 181,440 reachable 8-puzzle states (deepest {max_dist}), A* for the 15-puzzle')
    print(f'admissibility: 0 of 181,440 states where misplaced tiles, Manhattan, or linear conflict exceeds the true distance')
    print(f'8-puzzle, 100 random states (mean optimal length {mean(depths):.1f}, max {max(depths)}): every IDA* answer equals the exhaustive distance under every heuristic')
    print(f"  {'heuristic':>16} {'mean nodes generated':>21}")
    print(f'  {"zero (plain ID)":>16} {m_zero:>21,.0f}  on the {n_zero} instances of length at most 20 (Manhattan: {m_zero_paired:,.0f} on the same)')
    for name, v in (('misplaced tiles', m_mis), ('Manhattan', m_man), ('linear conflict', m_lc)):
        print(f'  {name:>16} {v:>21,.0f}')
    print(f'A* with Manhattan on the same 100: {mean(astar_nodes):,.0f} nodes generated, {mean(astar_peak):,.0f} states stored at peak; IDA* stores the path, at most {max(depths) + 1} states')
    print(f'iterations on a length-{length} instance: f-bounds {bounds}, nodes per iteration {iters}; the last complete iteration is {biggest_share:.0%} of {nodes:,} nodes and the final one, which stops at the goal, {last_share:.0%}; recursion depth {depth}')
    print(f"  {'15-puzzle':>9} {'length':>6} {'IDA* nodes':>10} {'IDA* stored':>11} {'A* nodes':>9} {'A* stored':>9}")
    for i, (l, ni, di, na, pa) in enumerate(rows15):
        print(f'  {i + 1:>9} {l:>6} {ni:>10,} {di:>11} {na:>9,} {pa:>9,}')
    print(f'breadth-first search: the 8-puzzle answer needs all {bfs_expanded:,} states expanded once (IDA* with Manhattan: {m_man:,.0f} nodes on average); the 15-puzzle has {space15:,} reachable states, not run')
    print(f'OK: IDA* optimal on 100 of 100 8-puzzle states and 4 of 4 15-puzzle instances; Manhattan {m_man:,.0f} nodes vs misplaced {m_mis:,.0f} vs plain iterative deepening {m_zero:,.0f}; '
          f'A* stores {mean(astar_peak):,.0f} states where IDA* stores a path; the last complete iteration is {biggest_share:.0%} of the work')
