import AprioriViz from '../viz/AprioriViz.jsx';
import Figure from '../components/Figure.jsx';
import code from '../../solutions/association_rule_mining_apriori_candidate_pruning.py?raw';
import { narration } from './association-rule-mining-apriori-candidate-pruning.narration.js';

export const content = {
  given:
    '5,000 baskets over 200 items, about 7.6 items each, generated by 25 hidden itemsets that are bought together (each planted in 3 to 8% of baskets), a few random items per basket, and one item present in 70% of all baskets. Find every itemset that appears in at least 2% of baskets, and the rules “if these, then that” with their confidence and lift.',
  task: 'Association rule mining, level by level: count the support of single items, then pairs, then triples, keeping the frequent ones, and read rules off the frequent sets. Apriori’s candidate pruning is the heuristic: every subset of a frequent itemset is itself frequent, so a size-k candidate is generated only from two frequent (k − 1)-sets that share a prefix, and is counted only if all of its (k − 1)-subsets were frequent. The lattice above an infrequent set is never touched.',
  constraint:
    'Measured against exhaustive subset counting (every subset of every basket up to size 5, 4,103,439 subsets tallied): Apriori finds the same 393 frequent itemsets at every size (63 / 143 / 122 / 53 / 12), all 25 planted itemsets among them. The prune: at size 3 the join proposes 1,914 candidates and 124 survive, 620,000 containment tests instead of 9,570,000; over levels 3 and up, 945,000 tests against 10,040,000 unpruned. Level 2, 1,953 pairs and 9,765,000 tests, cannot be pruned by subsets at all. Brute force over every 2- and 3-subset of 200 items would need 6,666,500,000 tests (not run). Rules at confidence 0.6: 1,438, with the planted rules at lift 6.5 to 21.9, and 194 rules pointing at the ubiquitous item with confidence 0.64 to 0.78 and lift 0.91 to 1.11. Eclat returns the same 393 sets touching 2,832,439 tid-set elements.',

  origins: (
    <p>
      Agrawal, Imieliński, and Swami posed the problem in{' '}
      <strong>1993</strong> (SIGMOD, &quot;Mining association rules
      between sets of items in large databases&quot;) from supermarket
      barcode data, and Agrawal and Srikant gave Apriori the next year
      (VLDB 1994, &quot;Fast algorithms for mining association
      rules&quot;), with Mannila, Toivonen, and Verkamo arriving at the
      same level-wise idea independently. The name is the principle:
      what is known a priori about a candidate&apos;s subsets decides
      whether it is counted. Park, Chen, and Yu (1995) attacked the
      pair-counting bottleneck with hashing (PCY); Toivonen (1996) with
      sampling; Zaki (1997) turned the database sideways into tid-sets
      (Eclat); Han, Pei, and Yin (2000) removed candidates altogether
      with the FP-tree. Brin, Motwani, and Silverstein (1997) added
      lift, because confidence alone had already produced the
      beer-and-diapers folklore and a great many rules that said
      nothing. Every recommender&apos;s &quot;frequently bought
      together&quot; and every log-mining tool&apos;s co-occurrence
      report descends from the level-wise count.
    </p>
  ),

  algoRole: (
    <p>
      Owns the <strong>counting</strong> and its exactness: support is
      a count over baskets, a rule&apos;s confidence is a ratio of two
      supports, and both are what they are, no model in between. The
      referee is exhaustive counting of every subset of every basket,
      4,103,439 tallies, and Apriori matches it{' '}
      <strong>at every size, 393 for 393</strong>, with every planted
      itemset recovered. The algorithm also owns the rules and their
      honesty check: confidence says how often the consequent follows
      the antecedent, lift divides that by how often the consequent
      appears anyway, and the planted rules score lift 6.5 to 21.9
      while 194 rules pointing at the item in 70% of baskets score
      confidence 0.64 to 0.78 and <strong>lift 0.91 to 1.11</strong>,
      the shape of a rule that has learned nothing.
    </p>
  ),
  heurRole: (
    <p>
      Supplies the <strong>reason not to count</strong>. If a set is
      frequent, so is every subset, so a candidate with one infrequent
      subset cannot be frequent and need not be counted. The join step
      proposes only sets whose two prefix-sharing (k − 1)-subsets are
      frequent, and the prune step checks the rest: at size 3,{' '}
      <strong>1,914 joined, 124 survive</strong>, and the level costs
      620,000 containment tests instead of 9,570,000; at size 4, 82
      become 53. Over levels 3 and up the tests fall from 10,040,000
      to 945,000. The prune cannot touch level 2: every subset of a
      pair of frequent items is a frequent item, so all 1,953 pairs are
      counted, 9,765,000 tests, the known bottleneck that Park, Chen,
      and Yu built hash filters for. The draft ran at 1% support,
      where noise alone made nearly every item frequent and level 2 was
      90 million of 168 million tests; at 2% the planted structure is
      what gets mined.
    </p>
  ),

  picture: (
    <p>
      A grocer wondering which products sell together, with a stack of
      five thousand receipts. Checking every possible bundle is
      hopeless; there are more triples of two hundred products than
      receipts by a factor of two hundred. So the grocer counts single
      products first and throws out the ones that sell fewer than a
      hundred times: nothing bought rarely can be part of a bundle
      bought often. Then pairs, but only pairs of survivors. Then
      triples, but only triples whose three pairs all survived. Each
      level is a scan of the receipts, and each level is far smaller
      than the last, because a bundle is only as common as its rarest
      part. What is known before counting decides what is worth
      counting.
    </p>
  ),

  steps: [
    <>
      <strong>Scan 1:</strong> count every item; keep those with
      support ≥ s (100 baskets here).
    </>,
    <>
      <strong>Join:</strong> merge frequent (k − 1)-sets sharing their
      first k − 2 items into k-candidates.
    </>,
    <>
      <strong>Prune:</strong> drop any candidate with a (k − 1)-subset
      that is not frequent.
    </>,
    <>
      <strong>Scan k:</strong> count the survivors against every
      basket; keep those with support ≥ s; repeat until none.
    </>,
    <>
      <strong>Rules:</strong> for each frequent set and each split,
      confidence = supp(set) / supp(antecedent), lift = confidence /
      P(consequent).
    </>,
  ],

  signals: [
    <>
      <strong>Sets that co-occur, no order, no model:</strong> baskets,
      symptom lists, feature flags, tags; the question is which
      combinations recur.
    </>,
    <>
      <strong>Sparse transactions over a large catalog:</strong> a few
      items per basket out of thousands, where the lattice is huge
      but the frequent part of it is tiny.
    </>,
    <>
      <strong>A support threshold you can defend:</strong> the count
      cuts off the noise floor; below it (1% here) everything is
      frequent and nothing is pruned.
    </>,
  ],
  baseline: (
    <>
      The honest baseline is <strong>exhaustive subset counting</strong>:
      tally every subset of every basket up to size 5, 4,103,439
      tallies here, exact and simple, and the referee on this page. It
      is fine for small baskets and explodes with basket size, since a
      30-item basket alone has 27,405 4-subsets.
    </>
  ),

  strength: (
    <>
      <strong>Exact, level-wise, and pruned where it counts.</strong> 393
      for 393 against exhaustive counting, 124 of 1,914 size-3
      candidates counted, levels 3 and up at a tenth of the unpruned
      cost, and five scans of the data no matter how large the
      lattice.
    </>
  ),
  weakness: (
    <>
      <strong>The pair level, the scans, and the threshold.</strong>{' '}
      Nothing prunes level 2, which is 9,765,000 of the 10,710,000
      tests here; every level is another full pass over the baskets;
      the support threshold is a cliff (951 frequent sets and 105
      million tests at 1%, 393 and 10.7 million at 2%); and the rules
      themselves need lift or a second measure, since confidence alone
      ranks 194 empty rules about the ubiquitous item above real ones.
    </>
  ),

  problem: 'Market-basket analysis',
  problemSlug: 'association-rules',
  rivals: [
    {
      name: 'Association rule mining × Apriori candidate pruning',
      isThisUnit: true,
      algoName: 'Association rule mining',
      cost: 'one scan per level; candidates × baskets tests',
      wins: (
        <>
          <strong>393 for 393 against the referee</strong>; levels 3+ at
          945,000 tests instead of 10,040,000.
        </>
      ),
      costs: (
        <>
          The unprunable pair level; a scan per level; a cliff at the
          threshold.
        </>
      ),
      when: 'Sparse baskets over a large catalog with a defensible support threshold.',
    },
    {
      name: 'FP-growth',
      algoName: 'FP-growth',
      cost: 'two scans, one prefix tree',
      wins: (
        <>
          No candidates at all: the baskets are compressed into a
          frequent-pattern tree and mined by recursive projection.
        </>
      ),
      costs: (
        <>
          The tree must fit in memory, and it is a harder program to
          write and to explain.
        </>
      ),
      when: 'Long baskets or low thresholds, where Apriori’s candidate sets and scans blow up.',
    },
    {
      name: 'ECLAT',
      algoName: 'ECLAT',
      cost: 'tid-set intersections, depth first',
      wins: (
        <>
          The same 393 sets from 2,832,439 tid-set elements touched;
          support is the size of an intersection, no scan needed.
        </>
      ),
      costs: (
        <>
          Tid-sets of frequent items are long; depth-first order loses
          Apriori&apos;s level-wide prune.
        </>
      ),
      when: 'Data that fits in memory as columns; dense, moderately sized transaction sets.',
    },
  ],
  neverUse: {
    name: 'Enumerating the catalog’s itemsets',
    why: (
      <>
        The direct reading of the problem is to list every possible
        itemset and count each one: 19,900 pairs and 1,313,400 triples
        of 200 items, checked against 5,000 baskets, is{' '}
        <strong>6,666,500,000 containment tests</strong> before a single
        4-set, and the count is not run on this page because it would
        take hours to confirm what Apriori gets from 10,710,000. The
        error is in the direction of the enumeration: the catalog&apos;s
        lattice has 2²⁰⁰ nodes and the baskets touch almost none of
        them. Count from the data toward the lattice, and let what is
        infrequent below decide what is never visited above.
      </>
    ),
  },

  contest: {
    instance:
      '5,000 baskets over 200 items (7.6 per basket), 25 planted itemsets, item 0 in 70% of baskets, minimum support 2% (100 baskets); referee: exhaustive subset counting, 4,103,439 subsets tallied',
    columns: ['candidates joined', 'after the prune', 'containment tests (pruned / unpruned)'],
    rows: [
      {
        method: 'size 1',
        values: ['200', '200', '·'],
        verdict: '63 frequent items',
      },
      {
        method: 'size 2',
        values: ['1,953', '1,953', '9,765,000 / 9,765,000'],
        verdict: 'nothing to prune: 143 frequent pairs',
      },
      {
        method: 'size 3',
        isThisUnit: true,
        values: ['1,914', '124', '620,000 / 9,570,000'],
        best: 1,
        verdict: '15× fewer tests; 122 frequent triples',
      },
      {
        method: 'size 4 / size 5',
        values: ['82 / 12', '53 / 12', '265,000 / 410,000; 60,000 / 60,000'],
        verdict: '53 and 12 frequent',
      },
      {
        method: 'total (5 scans)',
        values: ['4,161', '2,342', '10,710,000 / 19,805,000'],
        verdict: '393 frequent sets, identical to the referee',
      },
      {
        method: 'support 1% / 2% / 3% / 5%',
        values: ['·', '21,210 / 2,342 / 2,272 / 1,921', '105,050,000 / 10,710,000 / 10,360,000 / 8,605,000'],
        verdict: '951 / 393 / 375 / 187 frequent sets',
      },
      {
        method: 'rules at confidence 0.6',
        values: ['1,438 rules', 'planted: lift 6.5 to 21.9', '194 rules → item 0: lift 0.91 to 1.11'],
        verdict: 'confidence without lift is a trap',
      },
      {
        method: 'ECLAT (tid-set intersections)',
        values: ['·', '·', '2,832,439 tid elements touched'],
        verdict: 'the same 393 sets',
      },
    ],
    source:
      'python solutions/association_rule_mining_apriori_candidate_pruning.py prints this table and asserts: Apriori’s frequent sets and supports equal exhaustive counting at every size, with every planted set that the referee finds frequent found; the unpruned run returns the same sets at more tests, with levels 3 and up at least four times cheaper pruned; every planted rule has lift above 2 and the rules pointing at the ubiquitous item have confidence at least 0.6 and lift below 1.3; the support sweep is monotone; and Eclat returns the same sets.',
  },

  figure: (
    <Figure
      id="fig-apriori-levels"
      aspect="16 / 7"
      caption="Candidates per level, joined (amber) and surviving the subset prune (blue), on a log scale, with the frequent sets found (green). At size 2 the prune has nothing to do: 1,953 pairs of frequent items, all counted. At size 3 it strikes 1,790 of 1,914 candidates before any basket is read, and the level costs 620,000 containment tests instead of 9,570,000. Below the threshold, at 1% support, 951 sets are frequent and the run costs 105 million tests."
      cite={{
        text: 'R. Agrawal, T. Imieliński, A. Swami, "Mining association rules between sets of items in large databases," SIGMOD 1993. DOI 10.1145/170035.170072. R. Agrawal, R. Srikant, "Fast algorithms for mining association rules," VLDB 1994. J. Han, J. Pei, Y. Yin, "Mining frequent patterns without candidate generation," SIGMOD 2000.',
        href: 'https://doi.org/10.1145/170035.170072',
      }}
    >
      <svg viewBox="0 0 640 280" role="img" aria-label="Grouped bars per itemset size: candidates joined, candidates after pruning, and frequent sets, on a log scale, with the containment tests per level">
        {(() => {
          const x0 = 60;
          const y0 = 220;
          const h = 170;
          const levels = [
            { k: 1, join: 200, pruned: 200, freq: 63, tests: '·' },
            { k: 2, join: 1953, pruned: 1953, freq: 143, tests: '9.77M / 9.77M' },
            { k: 3, join: 1914, pruned: 124, freq: 122, tests: '0.62M / 9.57M' },
            { k: 4, join: 82, pruned: 53, freq: 53, tests: '0.27M / 0.41M' },
            { k: 5, join: 12, pruned: 12, freq: 12, tests: '0.06M / 0.06M' },
          ];
          const Y = (v) => y0 - (Math.log10(Math.max(v, 1)) / 3.5) * h;
          const groupW = 105;
          const barW = 26;
          return (
            <g>
              <line x1={x0} y1={y0} x2={x0 + levels.length * groupW} y2={y0} stroke="#9aa5bd" strokeOpacity="0.5" />
              {[1, 10, 100, 1000].map((v) => (
                <g key={v}>
                  <line x1={x0} y1={Y(v)} x2={x0 + levels.length * groupW} y2={Y(v)} stroke="#9aa5bd" strokeOpacity="0.15" />
                  <text x={x0 - 34} y={Y(v) + 4} fill="#9aa5bd" fontFamily="ui-monospace, monospace" fontSize="9">{v.toLocaleString()}</text>
                </g>
              ))}
              {levels.map((l, i) => {
                const gx = x0 + i * groupW + 10;
                return (
                  <g key={l.k}>
                    <rect x={gx} y={Y(l.join)} width={barW} height={y0 - Y(l.join)} fill="#f0b94b" fillOpacity="0.8" />
                    <rect x={gx + barW + 2} y={Y(l.pruned)} width={barW} height={y0 - Y(l.pruned)} fill="#5da2ff" fillOpacity="0.8" />
                    <rect x={gx + 2 * barW + 4} y={Y(l.freq)} width={barW} height={y0 - Y(l.freq)} fill="#62d98a" fillOpacity="0.8" />
                    <text x={gx + 12} y={y0 + 14} fill="#e9edf6" fontFamily="ui-monospace, monospace" fontSize="10">{`size ${l.k}`}</text>
                    <text x={gx - 4} y={y0 + 28} fill="#9aa5bd" fontFamily="ui-monospace, monospace" fontSize="9">{l.tests}</text>
                    <text x={gx - 2} y={Y(l.join) - 4} fill="#f0b94b" fontFamily="ui-monospace, monospace" fontSize="9">{l.join.toLocaleString()}</text>
                    {l.pruned !== l.join && <text x={gx + barW + 2} y={Y(l.pruned) - 4} fill="#5da2ff" fontFamily="ui-monospace, monospace" fontSize="9">{l.pruned}</text>}
                  </g>
                );
              })}
              <text x={x0} y="22" fill="#f0b94b" fontFamily="ui-monospace, monospace" fontSize="10">amber: joined</text>
              <text x={x0 + 110} y="22" fill="#5da2ff" fontFamily="ui-monospace, monospace" fontSize="10">blue: after the prune</text>
              <text x={x0 + 270} y="22" fill="#62d98a" fontFamily="ui-monospace, monospace" fontSize="10">green: frequent</text>
              <text x={x0 + 400} y="22" fill="#9aa5bd" fontFamily="ui-monospace, monospace" fontSize="10">below: tests pruned / unpruned</text>
              <text x={x0} y="262" fill="#9aa5bd" fontFamily="ui-monospace, monospace" fontSize="10">total 10,710,000 tests pruned vs 19,805,000 unpruned; brute force over all 2- and 3-subsets: 6,666,500,000</text>
            </g>
          );
        })()}
      </svg>
    </Figure>
  ),

  code,
  filename: 'association_rule_mining_apriori_candidate_pruning.py',
  Viz: AprioriViz,
  narration,
};
