import TreeViz from '../viz/TreeViz.jsx';
import Figure from '../components/Figure.jsx';
import code from '../../solutions/decision_tree_information_gain_splits.py?raw';
import { narration } from './decision-tree-information-gain-splits.narration.js';

export const content = {
  given:
    '2,000 labeled examples with six numeric features and one categorical feature, generated by a hidden rule that is itself a small tree (the answer turns on x₁, and only below a threshold of x₁ do the category and x₃ matter), with 10% of the labels flipped. Learn a classifier a person can read, and say how close it gets to the 89.3% that the noise allows.',
  task: 'A decision tree. Split the data on one feature at one threshold, recurse on each side, stop at a depth or a minimum leaf size, and predict the majority at each leaf. The heuristic is the split criterion: information gain, the drop in label entropy from the split, chosen greedily over every feature and every threshold at every node. A leaf is a rule you can say aloud; the whole tree is a flowchart.',
  constraint:
    'Measured against the generating rule on 2,000 held-out examples: the tree of depth 6 roots on x₁ at 0.600 (the rule says 0.6) and scores 88.4% against the Bayes rate of 89.3%; Gini impurity 88.9%, misclassification error 88.7%, random splits 66.5%. The identifier trap, with ID3-style multiway splits: information gain roots on a unique id column, grows 2,000 leaves, and scores 57.1%, the majority rate; gain ratio roots on x₁ and scores 89.2%; binary one-vs-rest splits are immune (89.0%). The depth sweep: depth 4 scores 88.6% on test; unlimited depth scores 100% on train and 81.2% on test with 230 leaves, and reduced-error pruning on 500 validation rows brings it to 6 leaves at 89.0%. Rivals on the same test set: a random forest of 30 trees 88.7%, Gaussian naive Bayes 75.3%, logistic regression 73.5%.',

  origins: (
    <p>
      Hunt, Marin, and Stone&apos;s Concept Learning System (1966) grew
      trees by hand-coded rules; Ross Quinlan&apos;s <strong>ID3</strong>{' '}
      (1979; &quot;Induction of decision trees,&quot; Machine Learning
      1(1), 1986) made the split criterion information gain, borrowed
      from Shannon, and made trees a learning method. Breiman,
      Friedman, Olshen, and Stone&apos;s CART (1984) used Gini impurity,
      binary splits, and cost-complexity pruning; Quinlan&apos;s C4.5
      (1993) added gain ratio, continuous thresholds, and pruning, and
      became the most-cited program in machine learning. The tree then
      became the atom of the strongest tabular methods: Breiman&apos;s
      random forests (2001), Friedman&apos;s gradient boosting (2001),
      and the XGBoost and LightGBM libraries that win tabular
      competitions today. The single tree survived alongside them
      because it is the model a regulator, a doctor, or a judge can
      read, which Rudin (2019) argued is not a luxury in high-stakes
      decisions.
    </p>
  ),

  algoRole: (
    <p>
      Owns the <strong>recursive partition</strong>: axis-aligned splits
      that carve the feature space into boxes, each with a majority
      label, so the model is a flowchart and every prediction comes with
      the path that produced it. The referee is the rule that generated
      the data. The tree of depth 6 <strong>roots on x₁ at 0.600</strong>,
      the rule&apos;s own threshold, and scores 88.4% on held-out data
      where the flipped labels cap any classifier at 89.3%. The algorithm
      also owns the failure mode: a tree grown to purity memorizes the
      noise, 100% on training and 81.2% on test with 230 leaves, and
      reduced-error pruning on 500 validation rows cuts it to{' '}
      <strong>6 leaves at 89.0%</strong>, a tree you can read in one
      breath.
    </p>
  ),
  heurRole: (
    <p>
      Supplies the <strong>question to ask next</strong>. At every node
      the tree tries every feature and every threshold and keeps the
      split with the largest information gain, the drop in label entropy
      weighted by how many examples go each way. On this data the
      criterion barely matters between the impurity measures: entropy
      88.4%, Gini 88.9%, misclassification error 88.7%, against random
      splits at 66.5%. Where it matters is the trap Quinlan built C4.5
      to escape. Add a unique identifier column and use multiway splits,
      one branch per value, and information gain is maximal at the id:
      every branch is pure, the &quot;tree&quot; is a lookup table with{' '}
      <strong>2,000 leaves and 57.1% test accuracy</strong>, the majority
      rate. Gain ratio divides by the split&apos;s own entropy, log₂ 2,000
      bits for the identifier, and roots on x₁ at 89.2%. The draft
      expected the trap under binary one-vs-rest splits too, and it did
      not appear (89.0%): isolating one row gains almost nothing, which
      is why CART-style binary splits never needed the ratio.
    </p>
  ),

  picture: (
    <p>
      Twenty questions, played against a pile of labeled cards with the
      answers written on the back, ten percent of them wrong. Which
      question first? Not the one that sounds clever: the one that,
      after the answer, leaves you least uncertain about the label, on
      average over both possible answers. That is information gain, and
      it is computed, not guessed, for every question the cards allow.
      Ask it, split the pile, and play the same game on each half. Stop
      when a pile is small or nearly one color. The tree of questions
      is the classifier, and anyone can follow it. The catch is the
      question &quot;what is the card&apos;s serial number?&quot;: it
      leaves you certain about every card in the pile and useless on
      every card outside it.
    </p>
  ),

  steps: [
    <>
      <strong>Node:</strong> count the labels; if depth, size, or
      purity says stop, return the majority.
    </>,
    <>
      <strong>Candidates:</strong> for each numeric feature, sort and
      try every midpoint; for the category, each value against the
      rest.
    </>,
    <>
      <strong>Gain:</strong> H(parent) − Σ (nᵢ/n) H(childᵢ); keep the
      largest (gain ratio divides by the split&apos;s own entropy).
    </>,
    <>
      <strong>Recurse</strong> on each side with the chosen test; a
      leaf predicts its majority.
    </>,
    <>
      <strong>Prune:</strong> replace any subtree by its majority leaf
      when validation accuracy does not drop.
    </>,
  ],

  signals: [
    <>
      <strong>Someone has to read the model:</strong> a path of three
      thresholds is an explanation; a weight vector is not.
    </>,
    <>
      <strong>Interactions and mixed types:</strong> thresholds on
      numbers, equality on categories, and rules that only apply on one
      side of another rule; logistic regression scored 73.5% here.
    </>,
    <>
      <strong>Noise in the labels:</strong> the tree will fit it; budget
      a depth limit or a validation set for pruning before you start.
    </>,
  ],
  baseline: (
    <>
      The honest baseline is <strong>a depth-one tree</strong>, the
      decision stump: one question, 74.8% on test here against the
      majority class at 57.0%. Every deeper level is bought with more
      leaves to read and more noise to fit; depth 4 already reaches
      88.6%.
    </>
  ),

  strength: (
    <>
      <strong>Readable, exact on interactions, near the noise ceiling.</strong>{' '}
      88.4% against a Bayes rate of 89.3%, the generating threshold
      recovered to three decimals, six leaves after pruning, and no
      feature scaling or encoding needed.
    </>
  ),
  weakness: (
    <>
      <strong>High variance, greedy, and axis-bound.</strong> Grown to
      purity it memorizes the noise (100% train, 81.2% test); a small
      change in the data can change the root and everything under it,
      which is why the forest averages 30 of them; the greedy criterion
      cannot see a split that only pays off two levels down (XOR-shaped
      rules defeat it); every boundary is axis-aligned, so a diagonal
      rule costs a staircase of leaves; and plain information gain
      prefers many-valued attributes until gain ratio corrects it.
    </>
  ),

  problem: 'Interpretable classification',
  problemSlug: 'classification',
  rivals: [
    {
      name: 'Decision tree × Information gain splits',
      isThisUnit: true,
      algoName: 'Decision tree',
      cost: 'O(d · n log n) per level to grow',
      wins: (
        <>
          <strong>88.4% and readable</strong>: the rule&apos;s root
          recovered, six leaves after pruning.
        </>
      ),
      costs: (
        <>
          Fits the noise without a depth limit or pruning; greedy;
          axis-aligned.
        </>
      ),
      when: 'When the model must be explained, or the rule is made of thresholds and interactions.',
    },
    {
      name: 'Random forest',
      algoName: 'Random forest',
      cost: '30 to 500 trees on bootstrap samples',
      wins: (
        <>
          Averages away the single tree&apos;s variance: 88.7% here with
          30 trees and no pruning at all.
        </>
      ),
      costs: (
        <>
          Thirty flowcharts are not a flowchart; only feature
          importances survive as explanation.
        </>
      ),
      when: 'Accuracy on tabular data with no need to read the model.',
    },
    {
      name: 'Naive Bayes',
      algoName: 'Naive Bayes',
      cost: 'one pass of counting',
      wins: (
        <>
          Trains in one pass, handles thousands of features, and gives
          calibrated-looking probabilities.
        </>
      ),
      costs: (
        <>
          Assumes features independent given the label: 75.3% here,
          because x₂ only matters when x₁ is large.
        </>
      ),
      when: 'Text and other high-dimensional sparse data, where independence is a workable lie.',
    },
    {
      name: 'Logistic regression',
      algoName: 'Logistic regression',
      cost: 'gradient steps over n × d',
      wins: (
        <>
          A single weight per feature, a probability out, a convex fit,
          and a confidence interval on every coefficient.
        </>
      ),
      costs: (
        <>
          One hyperplane cannot express &quot;x₂ matters only when x₁
          &gt; 0.6&quot;: 73.5% here.
        </>
      ),
      when: 'Additive effects, many features, and a need for calibrated probabilities.',
    },
  ],
  neverUse: {
    name: 'Multiway information gain with an identifier in play',
    why: (
      <>
        ID3 splits a categorical attribute into one branch per value,
        and information gain rewards the split whose branches are
        purest. A unique identifier, a row number, a customer id, a
        timestamp to the second, makes every branch perfectly pure, so
        its gain is the entire entropy of the labels and nothing else
        can compete. The result on this page: the root is the id column,
        the tree has <strong>2,000 leaves, one per training row</strong>,
        and every test row lands on a value never seen, so the tree
        predicts the majority class and scores 57.1%, exactly the
        majority rate. The fix is forty years old: gain ratio divides
        the gain by the split&apos;s own entropy, which for the identifier
        is log₂ 2,000 bits, and the same data then scores 89.2%. Or
        never let the id in.
      </>
    ),
  },

  contest: {
    instance:
      'a hidden tree rule over six numeric features and one category with 10% label noise; 2,000 train, 500 validation, 2,000 test; referee: the rule itself (Bayes rate 89.3%, majority class 57.0%)',
    columns: ['test accuracy', 'train accuracy', 'leaves'],
    rows: [
      {
        method: 'information gain, depth 6, min leaf 5',
        isThisUnit: true,
        values: ['88.4%', '·', '27'],
        best: 0,
        verdict: 'root x₁ at 0.600; the rule says 0.6',
      },
      {
        method: 'Gini / misclassification / random splits, depth 6',
        values: ['88.9% / 88.7% / 66.5%', '·', '14 / 6 / 39'],
        verdict: 'any impurity measure; not a coin',
      },
      {
        method: 'multiway gain with a unique id column',
        values: ['57.1%', '100%', '2,000'],
        verdict: 'the majority rate: a lookup table',
      },
      {
        method: 'gain ratio, same data',
        values: ['89.2%', '·', '·'],
        verdict: 'roots on x₁; Quinlan’s fix',
      },
      {
        method: 'depth 1 / 2 / 4 / 6 / 10 / unlimited (min leaf 1)',
        values: ['74.8 / 81.5 / 88.6 / 87.8 / 84.2 / 81.2%', '76.8 / 83.3 / 90.1 / 91.1 / 95.0 / 100%', '2 / 4 / 15 / 43 / 122 / 230'],
        verdict: 'past depth 4 the tree fits the flipped labels',
      },
      {
        method: 'unlimited, then reduced-error pruning on 500 rows',
        values: ['81.2% → 89.0%', '·', '230 → 6'],
        verdict: 'six leaves at the noise ceiling',
      },
      {
        method: 'random forest, 30 trees, 3 features per split',
        values: ['88.7%', '·', '30 trees'],
        verdict: 'the variance averaged away, unreadable',
      },
      {
        method: 'Gaussian naive Bayes / logistic regression',
        values: ['75.3% / 73.5%', '·', '·'],
        verdict: 'neither can say "only when x₁ > 0.6"',
      },
    ],
    source:
      'python solutions/decision_tree_information_gain_splits.py prints this table and asserts: the depth-6 tree roots on x₁ within 0.05 of 0.6 and scores within 3 points of the Bayes rate; entropy and Gini beat random splits by 5 points and agree within 3; with multiway splits the id column wins the root with one leaf per row and test accuracy within 3 points of the majority rate, while gain ratio and binary splits root on x₁ within 4 points of Bayes; the unlimited tree exceeds 99% on train and trails the depth-6 tree by 3 points on test, and pruning recovers 3 points with a third of the leaves; the forest is within 1 point of the tree and logistic regression at least 5 points below it.',
  },

  figure: (
    <Figure
      id="fig-tree-read"
      aspect="16 / 7"
      caption="The pruned tree, read aloud: is x₁ below 0.6? If not, is x₂ above 0.2? If so, is the category A or B, and is x₃ above 0.7? Six leaves, each a majority with its count, 89.0% on 2,000 held-out rows against a noise ceiling of 89.3%. Right: the depth sweep, training accuracy climbing to 100% while held-out accuracy peaks at depth 4 and falls to 81.2% for the unpruned tree; the identifier trap sits at the majority rate."
      cite={{
        text: 'J. R. Quinlan, "Induction of decision trees," Machine Learning 1(1), 1986. DOI 10.1007/BF00116251. J. R. Quinlan, C4.5: Programs for Machine Learning, Morgan Kaufmann, 1993. L. Breiman, J. Friedman, R. Olshen, C. Stone, Classification and Regression Trees, 1984.',
        href: 'https://doi.org/10.1007/BF00116251',
      }}
    >
      <svg viewBox="0 0 640 280" role="img" aria-label="A six-leaf decision tree drawn as boxes and arrows on the left; on the right, training and held-out accuracy against tree depth with the identifier trap marked">
        {[
          [150, 30, 'x₁ < 0.6 ?', '#5da2ff'],
          [70, 90, 'A or B ?', '#5da2ff'],
          [230, 90, 'x₂ > 0.2 ?', '#5da2ff'],
          [30, 150, 'x₃ > 0.7 ?', '#5da2ff'],
        ].map(([x, y, label, color], i) => (
          <g key={i}>
            <rect x={x - 42} y={y - 12} width="84" height="24" rx="4" fill="none" stroke={color} />
            <text x={x} y={y + 4} textAnchor="middle" fill="#e9edf6" fontFamily="ui-monospace, monospace" fontSize="10">{label}</text>
          </g>
        ))}
        {[
          [110, 150, '0', '#f0b94b'],
          [190, 150, '0', '#f0b94b'],
          [270, 150, '1', '#5da2ff'],
          [8, 210, '0', '#f0b94b'],
          [62, 210, '1', '#5da2ff'],
        ].map(([x, y, label, color], i) => (
          <g key={`l-${i}`}>
            <rect x={x - 14} y={y - 11} width="28" height="22" rx="11" fill={`${color}33`} stroke={color} />
            <text x={x} y={y + 4} textAnchor="middle" fill="#e9edf6" fontFamily="ui-monospace, monospace" fontSize="10">{label}</text>
          </g>
        ))}
        {[[150, 42, 70, 78], [150, 42, 230, 78], [70, 102, 30, 138], [70, 102, 110, 139], [230, 102, 190, 139], [230, 102, 270, 139], [30, 162, 8, 199], [30, 162, 62, 199]].map(([x1, y1, x2, y2], i) => (
          <line key={`e-${i}`} x1={x1} y1={y1} x2={x2} y2={y2} stroke="#9aa5bd" strokeOpacity="0.6" />
        ))}
        <text x="96" y="66" fill="#9aa5bd" fontFamily="ui-monospace, monospace" fontSize="9">yes</text>
        <text x="196" y="66" fill="#9aa5bd" fontFamily="ui-monospace, monospace" fontSize="9">no</text>
        <text x="10" y="248" fill="#62d98a" fontFamily="ui-monospace, monospace" fontSize="10">pruned: 6 leaves, 89.0% held-out (ceiling 89.3%)</text>
        <text x="10" y="264" fill="#9aa5bd" fontFamily="ui-monospace, monospace" fontSize="10">amber leaves predict 0, blue leaves predict 1</text>
        {(() => {
          const x0 = 360;
          const y0 = 230;
          const w = 250;
          const h = 170;
          const depths = [1, 2, 4, 6, 10, 14];
          const train = [76.8, 83.3, 90.1, 91.1, 95.0, 100];
          const test = [74.8, 81.5, 88.6, 87.8, 84.2, 81.2];
          const X = (i) => x0 + (i / (depths.length - 1)) * w;
          const Y = (a) => y0 - ((a - 50) / 50) * h;
          return (
            <g>
              <line x1={x0} y1={y0} x2={x0 + w} y2={y0} stroke="#9aa5bd" strokeOpacity="0.5" />
              <line x1={x0} y1={y0} x2={x0} y2={y0 - h} stroke="#9aa5bd" strokeOpacity="0.5" />
              <polyline points={train.map((a, i) => `${X(i)},${Y(a)}`).join(' ')} fill="none" stroke="#9aa5bd" strokeWidth="1.5" strokeDasharray="4 3" />
              <polyline points={test.map((a, i) => `${X(i)},${Y(a)}`).join(' ')} fill="none" stroke="#62d98a" strokeWidth="2" />
              <line x1={x0} y1={Y(89.3)} x2={x0 + w} y2={Y(89.3)} stroke="#5da2ff" strokeOpacity="0.6" strokeDasharray="2 3" />
              <line x1={x0} y1={Y(57.1)} x2={x0 + w} y2={Y(57.1)} stroke="#e2606c" strokeOpacity="0.8" strokeDasharray="2 3" />
              <text x={x0 + 4} y={Y(89.3) - 4} fill="#5da2ff" fontFamily="ui-monospace, monospace" fontSize="9">Bayes ceiling 89.3%</text>
              <text x={x0 + 4} y={Y(57.1) - 4} fill="#e2606c" fontFamily="ui-monospace, monospace" fontSize="9">identifier trap 57.1% (majority)</text>
              <text x={X(2) - 10} y={Y(100) + 4} fill="#9aa5bd" fontFamily="ui-monospace, monospace" fontSize="9">train</text>
              <text x={X(4) + 4} y={Y(84.2) + 12} fill="#62d98a" fontFamily="ui-monospace, monospace" fontSize="9">held-out</text>
              {depths.map((d, i) => (
                <text key={d} x={X(i) - 6} y={y0 + 12} fill="#9aa5bd" fontFamily="ui-monospace, monospace" fontSize="9">{d === 14 ? '∞' : d}</text>
              ))}
              <text x={x0 + 90} y={y0 + 26} fill="#9aa5bd" fontFamily="ui-monospace, monospace" fontSize="9">max depth</text>
            </g>
          );
        })()}
      </svg>
    </Figure>
  ),

  code,
  filename: 'decision_tree_information_gain_splits.py',
  Viz: TreeViz,
  narration,
};
